name: rna-seq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastp=0.20.1
  - samtools=1.14
  - rsem
  - bowtie=1.3.0
  - trinity=2.15.2
  - star
#- detonate
  - blast=2.17
#- yq
#- rnasamba
  - snakemake
  - python
#name: rna-seq
#channels:
#  - conda-forge
#  - bioconda
#  - defaults
#dependencies:
#  - fastp
#  - samtools
#  - rsem
#  - bowtie
#  - trinity
#  - detonate
#  - blast
#  - yq
#  - rnasamba
#  - snakemake
#  - python
